language: go

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.4
      - python-virtualenv

install:
  - go get -t ./...
  - virtualenv --python=python3.4 venv
  - venv/bin/pip install -r python/requirements.txt
  - venv/bin/pip install -e python

script:
  - go test -v ./...
  - venv/bin/py.test python/test

go:
  - 1.7.1
